### ISSUE TITLE
adjacent links separated by a space run together

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/wagtail_website#288]
See for example here:
https://wwwstaging.ietf.org/blog/anrp-2023/

**Comment by ghwood** [comment]
<img width="700" alt="image" src="https://github.com/ietf-tools/wagtail_website/assets/5347540/7c2cc804-29fc-4304-b5bb-adbe0714589c">

**Comment by mgax** [comment]
The problem seems to be introduced in https://github.com/ietf-tools/wagtail_website/commit/00eb01b: Django's [`{% spaceless %}`](https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#spaceless) template tag removes whitespace between HTML tags, including adjacent links. There is an unmaintained package, [django-smartspaceless](https://django-smartspaceless.readthedocs.io/en/latest/), that claims to preserve whitespace between inline elements, but I'm not sure it's worth the hassle. Here are some numbers for the homepage response size:

| Compression | original content  | `{% spaceless %}` | savings |
| ----------- | ----------------- | ----------------- | ------- |
| none        | 37093             | 24581             | 34%     |
| gzip        | 5677              | 5090              | 10%     |
| brotli      | 5662              | 5041              | 11%     |

Since most people will be accessing the website through Cloudflare, with browsers that support transport compression, perhaps the easy fix of removing `{% spaceless %}` is acceptable?

**Comment by rjsparks** [comment]
I have no objection to removing `{% spaceless %}`. Our _big_ content is not html.
