### ISSUE TITLE
enable top menu items to be changed and customized in the CMS admin interface

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/wagtail_website#96]
Currently only some "secondary" top menu elements are editable via the www.ietf.org/admin->settings web interface.

It should be possible to add/remove/edit secondary top menu items more generally, including adding new menu elements and links, and having drop-down options, similar to the "Tools" secondary top menu item, as shown in the screenshot.

<img width="327" alt="image" src="https://user-images.githubusercontent.com/5347540/123850182-b45d7200-d8e7-11eb-9406-0ad7d0a5acfe.png">

**Comment by kesara** [comment]
The current website has two sets of menu top-level menu:
* Primary top-level menu
* Secondary top-level menu
<img width="943" alt="top-level menu" src="https://user-images.githubusercontent.com/1027692/140400010-29071c19-5c30-4015-ba26-fca7444a6bf1.png">
These two menu sets are responsive and have different styling.

Only secondary top-level menu items are editable now. `admin -> settings -> secondary menu`
<img width="1030" alt="Screen Shot 2021-11-05 at 7 41 06 AM" src="https://user-images.githubusercontent.com/1027692/140400615-0be9ee10-ee2a-412d-b16e-5494b9a3d977.png">

The requirement of this issue is to have a similar capability for the primary menu items.
Users should be able to visit `admin -> settings -> primary menu` and change entries similar to the secondary menu.

Changes must preserve existing responsive design and stylings.
Dropdown menu names (Example: *ABOUT*, *TOPICS OF INTEREST*, etc) can stay hardcoded as it is, but menu items in those dropdown menus must be customizable similar to secondary menu items.

**Comment by kesara** [comment]
Available in production.
